apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../application

resources:
- namespace.yaml


patchesStrategicMerge:
- deployment.yaml

namespace: my_wanted_namespace